### ISSUE TITLE
怎么把项目跑起来呢

### ISSUE THREAD

**Issue by bigdogs** [ttentau/douyin#14]
大佬你好， 这个项目要怎么跑起来呢？ 可以补充到readme吗， 我在电脑上执行`npm run serve`发现运行失败，就不知道咋弄了

![image](https://user-images.githubusercontent.com/20614926/131964177-fa91c7df-6248-4207-931b-e5014c8d882d.png)

**Comment by ttentau** [comment]
@bigdogs 非常抱歉，由于需要一些真实的加载效果，数据我是在本地用php接口方式的返回的。现在还没有弄好，弄好了之后，我会把数据做成json文件提到项目里面，再通知你

**Comment by bigdogs** [comment]
@ttentau 辛苦辛苦
今天跑项目发现好像已经有一个mock数据了，但是好像还是有一个错误， 我不太清楚怎么解决
 ERROR  Failed to compile with 1 error                                                                                                                                                                 上午12:07:26

This dependency was not found:

* _vuex@4.0.2@vuex in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--0-1!./src/pages/message/Message.vue?vue&type=script&lang=js

To install it, you can run: npm install --save _vuex@4.0.2@vuex

**Comment by ttentau** [comment]
@bigdogs 现在可以了，数据用的是本地的了。更新一下代码基本就可以使用了。你报的那个错是导入vuex错误，我已经修复了

**Comment by bigdogs** [comment]
@ttentau 测试可以了，本地可以跑起来了～

**Comment by elarber** [comment]
这项目有意思哦
